[libraries]
slfj-api = { group = 'org.slf4j', name = 'slf4j-api', version = '1.7.36' }
logback-classic = { group = 'ch.qos.logback', name = 'logback-classic', version = '1.2.11' }
logback-encoder = { group = 'net.logstash.logback', name = 'logstash-logback-encoder', version = '6.6' }

[bundles]
logging = [
    'slfj-api',
    'logback-classic',
    'logback-encoder'
]
